### ISSUE TITLE
Connecting containers to service

### ISSUE THREAD

**Issue by gw17252009** [act28/pia-openvpn-proxy#11]
I hope this is the right place. I am wanting to use your container, but I have a few questions. I've tried elsewhere but no luck finding just the right info. Here is my snippet of my compose file with pia-openvpn-proxy and a client app:

https://pastebin.com/jeSYuetk

I am using caddy labels to reverse proxy my apps to my domain. Do the labels go in the client container or in the open vpn container?
Also should the open vpn container be in its own docker network? Or is that just a user choice?

Thanks.

**Comment by act28** [comment]
I'm closing this as (1) it's been a while, and (2) is installation/use case specific. It's more of a docker infrastructure issue. Feel free to open a different issue.
