### ISSUE TITLE
Error: UID and GID are not set

### ISSUE THREAD

**Issue by Silversurfer79** [act28/pia-openvpn-proxy#2]
UID and GID are not set.
appears over and over and doesnt stop, please advise.

So if I oput in UID: 1001 and GID: 2001 it stops erroring and loads with more errors. What should those values be?

**Comment by Silversurfer79** [comment]
So if I oput in UID: 1001 and GID: 2001 it stops erroring and loads with more errors. What should those values be?

**Comment by act28** [comment]
RTFM: these are optional

How to find your own UID/GID
https://lmgtfy.com/?q=how+to+find+your+own+uid+gid+linux

**Comment by Silversurfer79** [comment]
Cheeky, im not asking  how to find the values, Im asking what they should be? Im using docker and wanting to know what to use.

**Comment by act28** [comment]
What they should be, is what they are currently set to - for your current user. :)
https://medium.com/@mccode/understanding-how-uid-and-gid-work-in-docker-containers-c37a01d01cf
