### ISSUE TITLE
openvpn does not start in the latest version 

### ISSUE THREAD

**Issue by paralet** [act28/pia-openvpn-proxy#21]
hello,
Thank you so much for your work. a great product
openvpn does not start in the latest version pia-openvpn-proxy:2.1.0
in the "docker-compose logs -f" logs there is nothing about openvpn, only a proxy

**Comment by act28** [comment]
That's fixed now in 2.1.1.

For some reason, I can't figure out why, `pidof` seems to kill the script. I've removed it for now. The longer term plan is to use PIA's opensourced scripts to manage the openvpn connection, or drop openvpn support altogether. Wireguard has been in place for a while now and is pretty stable.
