### ISSUE TITLE
ERROR: No such file or directory

### ISSUE THREAD

**Issue by Silversurfer79** [act28/pia-openvpn-proxy#3]
ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)
Exiting due to fatal error

Any ideas?

**Comment by act28** [comment]
Nope. 
1. OS type and docker versions?
2. Describe the steps required to replicate the issue?
3. Provide the container's log output?

**Comment by Silversurfer79** [comment]
1. OS is Synology - DSM 6.2.2-24922 Update 4
    Docker Version - 18.09.0-0506
2. Download image, Launch Container, Add port (8888 local) - internal (8118 default), Add User / Password and Region (UK London), UID and GID added (UID: 1001 - GID: 2001) wihtout image wont boot and added local netwrok (LOCAL_NETWORK in my case 10.55.0.0/24).
3. will do shortly - after i clean them

**Comment by Silversurfer79** [comment]
![image](https://user-images.githubusercontent.com/58236890/74992368-d4ea0200-543f-11ea-8726-45567839a12f.png)

**Comment by Silversurfer79** [comment]
Didnt have admin permissions enabled, that sorted it ;-)
